scss_files: 'scss/**/*.css.scss'

exclude:
   - 'scss/_base_reset.scss'
   - 'scss/grid/*'
   - 'scss/_layout_grid.scss'

linters:
  ImportantRule:
    enabled: false

  NestingDepth:
    max_depth: 4

  SelectorFormat:
    convention: hyphenated_BEM

  Indentation:
    width: 2
