language: node_js
node_js:
  - '12.14.0'
before_install:
  - rvm install 2.4.0
  # make sure bundler@1 is installed
  # https://docs.travis-ci.com/user/languages/ruby/#bundler
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install:
  - gem install percy-cli
  - gem install sass
  - bundle install
  - yarn install
before_script:
  - yarn run build
script:
  - yarn run test
  - yarn run build-docs
  - percy snapshot --widths "375,1280" docs/_site/
notifications:
  irc:
    channels:
      - 'chat.freenode.net#vanilla-framework'
    on_success: change
    on_failure: always
  slack:
    rooms:
      - vanillaframework:wvRcrt4C6ODhvHxrUkTaKlD5#general
