name: Vanilla framework - Examples

baseurl: /vanilla-framework

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: ["*.md", "*.scss", "node_modules", "package.json", "Gemfile", "Gemfile.lock", "gulpfile.js", "gulp", "LICENSE"]

