name: Vanilla framework - Examples

baseurl: /vanilla-framework

includes:
  - ../build/css

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [src]

